#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2010 Santhosh Thottingal <santhosh.thottingal@gmail.com>
fonts = {
            "AnjaliOldLipi":{
                    "Name": u"അഞ്ജലി ഓള്‍ഡ് ലിപി", 
                    "License":"GPL", 
                    "Author" :"Kevin", 
                    "ttf" : "AnjaliOldLipi.ttf", 
                    "eot" : "AnjaliOldLipi.eot", 
                    "woff" : "AnjaliOldLipi.woff", 
                    "Variants":"Normal, Bold", 
                    "Scripts":"English, Malayalam", 
                    "Language":"Malayalam", 
                    "Glyphs":"3330:3455"
                    }, 
            "Meera":{
                    "Name": u"മീര", 
                    "License":"GPL", 
                    "Author" :"Hussain K H", 
                    "ttf" : "Meera.ttf", 
                    "eot" : "Meera.eot", 
                    "woff" : "Meera.woff", 
                    "Variants":"Normal, Bold", 
                    "Scripts":"English, Malayalam", 
                    "Language":"Malayalam", 
                    "Glyphs":"3330:3455"
                    }, 
            "Rachana":{
                    "Name": u"രചന", 
                    "License":"GPL", 
                    "Author" :"Hussain K H", 
                    "ttf" : "Rachana.ttf", 
                    "eot" : "Rachana.eot", 
                    "woff" : "Rachana.woff", 
                    "Variants":"Normal, Bold", 
                    "Scripts":"English, Malayalam", 
                    "Language":"Malayalam", 
                    "Glyphs":"3330:3455"
                    } , 
             "Kalyani":{
                    "Name": u"കല്യാണി", 
                    "License":"GPL", 
                    "Author" :"Hussain K H", 
                    "ttf" : "Kalyani.ttf", 
                    "eot" : "Kalyani.eot", 
                    "woff" : "Kalyani.woff", 
                    "Variants":"Normal, Bold", 
                    "Scripts":"English, Malayalam", 
                    "Language":"Malayalam", 
                    "Glyphs":"3330:3455"
                    } , 
              "Suruma":{
                    "Name": u"സുറുമ", 
                    "License":"GPL", 
                    "Author" :"Suresh P", 
                    "ttf" : "Suruma.ttf", 
                    "eot" : "Suruma.eot", 
                    "woff" : "Suruma.woff", 
                    "Variants":"Normal, Bold", 
                    "Scripts":"English, Malayalam", 
                    "Language":"Malayalam", 
                    "Glyphs":"3330:3455"
                    } , 
              "LohitMalayalam":{
                    "Name": u"ലോഹിത് മലയാളം", 
                    "License":"GPL v2", 
                    "Author" :"Red Hat Inc.", 
                    "ttf" : "LohitMalayalam.ttf", 
                    "eot" : "LohitMalayalam.eot", 
                    "woff" : "LohitMalayalam.woff", 
                    "Variants":"Normal, Bold", 
                    "Scripts":"English, Malayalam", 
                    "Language":"Malayalam", 
                    "Glyphs":"3330:3455"
                    } , 
              "SamyakMalayalam":{
                    "Name": u"സമ്യക്‍ മലയാളം", 
                    "License":"GPL", 
                    "Author" :"", 
                    "ttf" : "SamyakMalayalam.ttf", 
                    "eot" : "SamyakMalayalam.eot", 
                    "woff" : "SamyakMalayalam.woff", 
                    "Variants":"Normal, Bold", 
                    "Scripts":"English, Malayalam", 
                    "Language":"Malayalam", 
                    "Glyphs":"3330:3455"
                    } , 
              "RaghuMalayalam":{
                    "Name": u"രഘു മലയാളം", 
                    "License":"GPL", 
                    "Author" :"", 
                    "ttf" : "RaghuMalayalam.ttf", 
                    "eot" : "RagghuMalayalam.eot", 
                    "woff" : "RaghuMalayalam.woff", 
                    "Variants":"Normal, Bold", 
                    "Scripts":"English, Malayalam", 
                    "Language":"Malayalam", 
                    "Glyphs":"3330:3455"
                    }   , 
            "Rufscript":{
                    "Name": "Rufscript", 
                    "License":"GPL", 
                    "Author" :"Hiran Venugopal", 
                    "ttf" : "Rufscript.ttf", 
                    "eot" : "Rufscript.eot", 
                    "woff" : "Rufscript.woff", 
                    "Variants": "Regular", 
                    "Scripts": "English", 
                    "Language":"English", 
                    "Glyphs":"65:122"
                    }            , 
           "Perizia":{
                    "Name": "Perizia", 
                    "License":"GPL", 
                    "Author" :"Hiran Venugopal", 
                    "ttf" : "Perizia.ttf", 
                    "eot" : "Perizia.eot", 
                    "woff" : "Perizia.woff", 
                    "Variants": "Normal, Bold", 
                    "Scripts": "English", 
                    "Language":"English", 
                    "Glyphs":"65:122"
                    } , 
           "Dyuthi":{
                    "Name": u"ദ്യുതി", 
                    "License":"GPL", 
                    "Author" :"Hiran Venugopal", 
                    "ttf" : "Dyuthi.ttf", 
                    "eot" : "Dyuthi.eot", 
                    "woff" : "Dyuthi.woff", 
                    "Variants": "Normal, Bold", 
                    "Scripts": "English,Malayalam", 
                    "Language":"Malayalam", 
                    "Glyphs":"3330:3455"
                    }, 
            "Kedage":{
                    "Name": u"ಕೇದಗೆ", 
                    "License":"GPL", 
                    "Author":"Indian Institute of Science, Bangalore", 
                    "ttf": "Kedage.ttf", 
                    "eot": "Kedage.eot", 
                    "woff": "Kedage.woff", 
                    "Variants": "Normal", 
                    "Scripts": "English,Kannada", 
                    "Language": "Kannada", 
                    "Glyphs":"3202:3311"
                   }, 
            "Malige":{
                    "Name": u"ಮಲ್ಲಿಗೆ", 
                    "License":"GPL", 
                    "Author":"Indian Institute of Science, Bangalore", 
                    "ttf":"Malige.ttf", 
                    "eot":"Malige.eot", 
                    "woff":"Malige.woff", 
                    "Variants": "Normal", 
                    "Scripts":"English,Kannada", 
                    "Language":"Kannada", 
                    "Glyphs":"3202:3311"
                  }, 
            "LohitKannada":{
                    "Name": u"ಲೋಹಿತ್ ಕನ್ನಡ", 
                    "License":"GPL v2", 
                    "Author":"Red Hat Inc.", 
                    "ttf":"LohitKannada.ttf", 
                    "eot":"LohitKannada.eot", 
                    "woff":"LohitKannada.woff", 
                    "Variants":"Regular", 
                    "Scripts":"English,Kannada,Devanagari", 
                    "Language":"Kannada", 
                    "Glyphs":"3202:3314"
                  }, 
           "LohitTamil":{
                    "Name": u"லௌஹித் தமிழ்", 
                    "License":"GPL v2", 
                    "Author":"Red Hat Inc.", 
                    "ttf":"LohitTamil.ttf", 
                    "eot":"LohitTamil.eot", 
                    "woff":"LohitTamil.woff", 
                    "Variants":"Regular", 
                    "Scripts":"English,Tamil", 
                    "Language":"Tamil", 
                    "Glyphs":"2946:3066"
                  },
          "SamyakTamil":{
                    "Name": "Samyak Tamil", 
                    "License":"GPL v3", 
                    "Author":"Rahul Bhalerao, Sandeep Shedmake, Bageshri Salvi, Pravin Satpute", 
                    "ttf":"Samyak-Tamil.ttf", 
                    "eot":"Samyak-Tamil.eot", 
                    "woff":"Samyak-Tamil.woff", 
                    "Variants":"Regular", 
                    "Scripts":"English,Tamil", 
                    "Language":"Tamil", 
                    "Glyphs":"2946:3066"
                  }, 
           "Thenee":{
                    "Name": "Thenee", 
                    "License":"GPL v2", 
                    "Author":"Umar Thamby", 
                    "ttf":"TheneeUni.ttf", 
                    "eot":"TheneeUni.eot", 
                    "woff":"TheneeUni.woff", 
                    "Variants":"Regular", 
                    "Scripts":"English,Tamil", 
                    "Language":"Tamil", 
                    "Glyphs":"2946:3066"
                  },  
           "Thendral":{
                    "Name": "Thendral", 
                    "License":"GPL v2", 
                    "Author":"Umar Thamby", 
                    "ttf":"ThendralUni.ttf", 
                    "eot":"ThendralUni.eot", 
                    "woff":"ThendralUni.woff", 
                    "Variants":"Regular", 
                    "Scripts":"English,Tamil", 
                    "Language":"Tamil", 
                    "Glyphs":"2946:3066"
                  },   
             "Vaigai":{
                    "Name": "Vaigai", 
                    "License":"GPL v2", 
                    "Author":"Umar Thamby", 
                    "ttf":"VaigaiUni.ttf", 
                    "eot":"VaigaiUni.eot", 
                    "woff":"VaigaiUni.woff", 
                    "Variants":"Regular", 
                    "Scripts":"English,Tamil", 
                    "Language":"Tamil", 
                    "Glyphs":"2946:3066"
                  },                                  
          "LohitOriya":{
                    "Name": u"Lohit Oriya", 
                    "License":"GPL v2", 
                    "Author":"Red Hat Inc.", 
                    "ttf":"LohitOriya.ttf", 
                    "eot":"LohitOriya.eot", 
                    "woff":"LohitOriya.woff", 
                    "Variants":"Regular", 
                    "Scripts":"English,Odia", 
                    "Language":"Oriya", 
                    "Glyphs":"2817:2929"
                  },
           "Utkal":{
                    "Name": u"Utkal", 
                    "License":"GPL", 
                    "Author":"Andy White, Rajesh Pradhan", 
                    "ttf":"utkal.ttf", 
                    "eot":"utkal.eot", 
                    "woff":"utkal.woff", 
                    "Variants":"Regular", 
                    "Scripts":"English,Odia", 
                    "Language":"Oriya", 
                    "Glyphs":"2817:2929"
                  },       
           "SamyakOriya":{
                    "Name": u"Samyak Oriya", 
                    "License":"GPL v3", 
                    "Author":"Rahul Bhalerao, Sandeep Shedmake, Bageshri Salvi, Pravin Satpute", 
                    "ttf":"Samyak-Oriya.ttf", 
                    "eot":"Samyak-Oriya.eot", 
                    "woff":"Samyak-Oriya.woff", 
                    "Variants":"Regular", 
                    "Scripts":"English,Odia", 
                    "Language":"Oriya", 
                    "Glyphs":"2817:2929"
                  },        
           "LohitHindi":{
                    "Name": u"लौहित हिंदी", 
                    "License":"GPL v2", 
                    "Author":"Red Hat Inc.", 
                    "ttf":"LohitHindi.ttf", 
                    "eot":"LohitHindi.eot", 
                    "woff":"LohitHindi.woff", 
                    "Variants":"Regular", 
                    "Scripts":"English,Devanagari", 
                    "Language":"Hindi", 
                    "Glyphs":"2304:2431"
                  }, 
            "Samyak-Devanagari":{
                    "Name": u"सम्यक  हिंदी", 
                    "License":"GPL v2", 
                    "Author":"Rahul Bhalerao,Sandeep Shedmake,Bageshri Salvi,Pravin Satpute", 
                    "ttf":"SamyakDevanagari.ttf", 
                    "eot":"SamyakDevanagari.eot", 
                    "woff":"SamyakDevanagari.woff", 
                    "Variants":"Regular", 
                    "Scripts":"English,Devanagari", 
                    "Language":"Hindi", 
                    "Glyphs":"2304:2431"
                  }, 
         "Samyak-Gujarati":{
                    "Name": u"Samyak Gujarati", 
                    "License":"GPL v2", 
                    "Author":"Rahul Bhalerao,Sandeep Shedmake,Bageshri Salvi,Pravin Satpute", 
                    "ttf":"SamyakGujarati.ttf", 
                    "eot":"SamyakGujarati.eot", 
                    "woff":"SamyakGujarati.woff", 
                    "Variants":"Regular", 
                    "Scripts":"English,Gujarati", 
                    "Language":"Gujarati", 
                    "Glyphs":"2689:2801"
                  }, 
      "LohitGujarati":{
                    "Name": u"Lohit Gujarati", 
                    "License":"GPL v2", 
                    "Author":"Red Hat Inc.", 
                    "ttf":"LohitGujarati.ttf", 
                    "eot":"LohitGujarati.eot", 
                    "woff":"LohitGujarati.woff", 
                    "Variants":"Regular", 
                    "Scripts":"English,Gujarati", 
                    "Language":"Gujarati", 
                    "Glyphs":"2689:2801"
                  }, 
       "LohitBengali":{
                    "Name": u"Lohit Bengali", 
                    "License":"GPL v2", 
                    "Author":"Red Hat Inc.", 
                    "ttf":"LohitBengali.ttf", 
                    "eot":"LohitBengali.eot", 
                    "woff":"LohitBengali.woff", 
                    "Variants":"Regular", 
                    "Scripts":"English, Bengali", 
                    "Language":"Bengali", 
                    "Glyphs":"2433:2555"
                  }, 
         "LohitTelugu":{
                    "Name": u"Lohit Telugu", 
                    "License":"GPL v2", 
                    "Author":"Red Hat Inc.", 
                    "ttf":"LohitBengali.ttf", 
                    "eot":"LohitBengali.eot", 
                    "woff":"LohitBengali.woff", 
                    "Variants":"Regular", 
                    "Scripts":"English, Telugu", 
                    "Language":"Telugu", 
                    "Glyphs":"3073:3199"
                  },
        "LohitBengali":{
                    "Name": u"Lohit Bengali", 
                    "License":"GPL v2", 
                    "Author":"Red Hat Inc.", 
                    "ttf":"LohitBengali.ttf", 
                    "eot":"LohitBengali.eot", 
                    "woff":"LohitBengali.woff", 
                    "Variants":"Regular", 
                    "Scripts":"English, Bengali", 
                    "Language":"Bengali", 
                    "Glyphs":"2433:2555"
                  }, 
      "Ubuntu-B":{
                    "Name":"Ubuntu Bold Font", 
                    "License":"UFL v1.0 (Ubuntu Font License)", 
                    "Author":"Canonical Ltd.", 
                    "ttf":"ubuntu-b.ttf", 
                    "eot":"ubuntu-b-webfont.eot", 
                    "woff":"ubuntu-b-webfont.woff", 
                    "Variants":"Bold", 
                    "Scripts":"English,Greek,Latin,Cyrillic,Latin", 
                    "Language":"English", 
                    "Glyphs":"65:122"
        
                 }, 
      "Ubuntu-BI":{
                    "Name":"Ubuntu Bold Italic Font", 
                    "License":"UFL v1.0 (Ubuntu Font License)", 
                    "Author":"Canonical Ltd.", 
                    "ttf":"ubuntu-bi.ttf", 
                    "eot":"ubuntu-bi-webfont.eot", 
                    "woff":"ubuntu-bi-webfont.woff", 
                    "Variants":"Bold Italic", 
                    "Scripts":"English,Greek,Latin,Cyrillic,Latin", 
                    "Language":"English", 
                    "Glyphs":"65:122"
        
                 }, 
       "Ubuntu-I":{
                    "Name":"Ubuntu Italic Font", 
                    "License":"UFL v1.0 (Ubuntu Font License)", 
                    "Author":"Canonical Ltd.", 
                    "ttf":"ubuntu-i.ttf", 
                    "eot":"ubuntu-i-webfont.eot", 
                    "woff":"ubuntu-i-webfont.woff", 
                    "Variants":"Italic", 
                    "Scripts":"English,Greek,Latin,Cyrillic,Latin", 
                    "Language":"English", 
                    "Glyphs":"65:122"
        
                 }, 
       "Ubuntu-R":{
                    "Name":"Ubuntu Regular Font", 
                    "License":"UFL v1.0 (Ubuntu Font License)", 
                    "Author":"Canonical Ltd.", 
                    "ttf":"ubuntu-r.ttf", 
                    "eot":"ubuntu-r-webfont.eot", 
                    "woff":"ubuntu-r-webfont.woff", 
                    "Variants":"Regular", 
                    "Scripts":"English,Greek,Latin,Cyrillic,Latin", 
                    "Language":"English", 
                    "Glyphs":"65:122"
        
                 },
        "Pagul":{
                    "Name":"Pagul", 
                    "License":"GPLV3", 
                    "Author":"Prabu M Rengachari", 
                    "ttf":"Pagul.ttf", 
                    "eot":"Pagul.eot", 
                    "woff":"Pagul.woff", 
                    "Variants":"Regular", 
                    "Scripts":"English,Sourashtra", 
                    "Language":"Sourashtra", 
                    "Glyphs":"43136:43225"
        
                 },
	"Eeyek":{
                    "Name":"Eeyek", 
                    "License":"GPLV2", 
                    "Author":"Pravabati Chingangbam and Tabish", 
                    "ttf":"Eeyek.ttf", 
                    "eot":"Eeyek.eot", 
                    "woff":"Eeyek.woff", 
                    "Variants":"Regular", 
                    "Scripts":"Meetei Mayek", 
                    "Language":"Manipuri", 
                    "Glyphs":"43968:44031"
                 }                 
        }
